language: python
services:
  - redis-server
matrix:
  include:
    - python: "3.6"
      env: DJANGO="django>1.5"
    - python: "3.5"
      env: DJANGO="django>1.5"
    - python: "3.4"
      env: DJANGO="django>1.5"
    - python: "2.7"
      env: DJANGO="django>=1.4,<2.0"
    - python: "pypy"
      env: DJANGO="django>=1.4,<2.0"
    # Adding jobs for ppc64le architecture
    - python: "3.6"
      arch: ppc64le
      env: DJANGO="django>1.5"
    - python: "3.5"
      arch: ppc64le
      env: DJANGO="django>1.5"
    - python: "3.4"
      arch: ppc64le
      env: DJANGO="django>1.5"
    - python: "2.7"
      arch: ppc64le
      env: DJANGO="django>=1.4,<2.0"
install:
  - pip install $DJANGO
  - pip install -q redis
script: python setup.py nosetests
